---
# defaults file for db
- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  tasks:
  - name: install progress
    command: "yum install -y postgresql-server"

  #- name: install postgres
  #  yum:
  #    name: postgresql-server
  #    state: latest
  # only run the next 2 tasks once!
  - name: initilize postgres
    command: postgresql-setup initdb

  - name: initilize postgres some more
    command: chkconfig postgresql on
    
  - name: start postgres
    service:
      name: postgresql.service
      state: started